name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
        exclude:
          # Exclude combinations that are not commonly used
          - os: windows
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          APP_NAME=duplfiles2link
          if [ "${{ matrix.os }}" = "windows" ]; then
            APP_NAME="${APP_NAME}.exe"
          fi
          go build -v -ldflags="-s -w -X duplfiles2link/pkg/duplfiles2link.Version=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')" -o "${APP_NAME}" .
          
          # Create zip file
          ZIP_NAME="duplfiles2link-${{ matrix.os }}-${{ matrix.arch }}.zip"
          zip -r "${ZIP_NAME}" "${APP_NAME}" LICENSE README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: duplfiles2link-${{ matrix.os }}-${{ matrix.arch }}
          path: duplfiles2link-${{ matrix.os }}-${{ matrix.arch }}.zip
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release notes
        id: release_notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "### duplfiles2link $VERSION" > release_notes.md
          echo "" >> release_notes.md
          echo "Automatically built binaries for multiple platforms." >> release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION }}
          body_path: release_notes.md
          files: artifacts/**/*.zip
          draft: false
          prerelease: false 