name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          cache: true

      - name: Build Windows binary
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          APP_NAME="duplfiles2link.exe"
          go build -v -ldflags="-s -w -X duplfiles2link/pkg/duplfiles2link.Version=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')" -trimpath -o "${APP_NAME}" .
          
          # Install 7-Zip
          sudo apt-get update && sudo apt-get install -y p7zip-full
          
          # Create 7z archive with maximum compression
          Z7_NAME="duplfiles2link-windows-amd64.7z"
          7z a -t7z -mx=9 "${Z7_NAME}" "${APP_NAME}" LICENSE README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: duplfiles2link-windows-amd64
          path: duplfiles2link-windows-amd64.7z
          retention-days: 1

  release:
    name: Create Release
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release notes
        id: release_notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "### duplfiles2link $VERSION" > release_notes.md
          echo "" >> release_notes.md
          echo "Windows binary is available for download." >> release_notes.md
          echo "" >> release_notes.md
          echo "Note: This application is designed for Windows systems only." >> release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION }}
          body_path: release_notes.md
          files: artifacts/**/*.7z
          draft: false
          prerelease: false 